Fixes the second param completion
Azure/azure-cli-shell pull request #40
Opened 2017-04-05 22:41 UTC by oakeyc

#15, #10

2017-04-05 22:41 UTC, msftclas commented
@oakeyc,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-07 22:30 UTC, tjprescott requested changes
Does this actually fix anything?  The only change I see is the addition of a single blank line.

2017-04-07 22:30 UTC, tjprescott commented on azclishell/az_completer.py
> +
Unless GitHub is being super weird... how does adding a blank line fix all these issues? 😅

2017-04-07 22:43 UTC, oakeyc commented on azclishell/az_completer.py
> +
Haha, I don't know why it's doing that, but it does. In commit: https://github.com/Azure/azure-cli-shell/pull/40/commits/41c56d53893f7364c5baac332d6dbf8557d8908c this is the bulk of what I did.

2017-04-07 22:54 UTC, derekbekoe commented on azclishell/az_completer.py
> +
Those changes were already merged in in a different PR it seems.

2017-04-07 22:55 UTC, tjprescott commented on azclishell/az_completer.py
> +
That's one way of doing it.

2017-04-07 22:55 UTC, tjprescott approved these changes

2017-04-07 23:02 UTC, derekbekoe commented on azclishell/az_completer.py
> +
However, it doesn't look like it has addressed everything. e.g. https://github.com/Azure/azure-cli-shell/issues/9
@oakeyc please take a look.

2017-04-10 06:20 UTC, merged