History
Azure/azure-cli-shell pull request #48
Opened 2017-04-06 00:37 UTC by oakeyc

#24

2017-04-06 00:37 UTC, msftclas commented
@oakeyc,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-06 23:46 UTC, derekbekoe requested changes

2017-04-06 23:46 UTC, derekbekoe commented on azclishell/az_completer.py
> +        for param in sorted(list(self.gen_global_param_completions(text)), key=lambda a: a.text,):
This should be in a helper method that you call.
Something like `sorted_completions(...)`

2017-04-06 23:46 UTC, derekbekoe commented on azclishell/configuration.py
> +    SELECT_SYMBOL['default'] + '[cmd]' : "set a scope",
These keys should be changed as now the meaning as changed.
`set-scope` `unset-scope` maybe.
Defaults mean something else in the CLI.

2017-04-07 05:19 UTC, oakeyc commented
changes made

2017-04-07 17:37 UTC, derekbekoe requested changes
One more thing.
The version no.s don't match up.

Would suggest not changing the version no. in PRs otherwise you'll get version mismatches depending on the order PRs are merged.
Only change version no.s before a release in a release PR.

2017-04-07 17:37 UTC, derekbekoe commented on azclishell/__init__.py
> +__version__ = '0.1.1a31'
This version does not match the one in setup.py

2017-04-07 17:40 UTC, derekbekoe approved these changes

2017-04-07 17:46 UTC, merged