Setup file added for pypi
Azure/azure-cli-shell pull request #60
Opened 2017-04-10 22:30 UTC by oakeyc

2017-04-10 22:30 UTC, msftclas commented
@oakeyc,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-10 22:31 UTC, derekbekoe requested changes
The setup.cfg looks good but you included a version change.

2017-04-10 22:31 UTC, derekbekoe commented on azclishell/__init__.py
> +__version__ = '0.1.1c3'
The versions wouldn't be in sync again.

2017-04-10 23:18 UTC, oakeyc commented
I wanted to increment to version 0.1.1c3

2017-04-10 23:21 UTC, derekbekoe commented
@oakeyc but then the version in setup.py would also have to change right?

2017-04-11 18:25 UTC, oakeyc commented
@derekbekoe changes made

2017-04-11 18:42 UTC, derekbekoe approved these changes

2017-04-11 19:30 UTC, merged