Meaningful exit code message
Azure/azure-cli-shell pull request #66
Opened 2017-04-11 22:05 UTC by oakeyc

fixes #43

2017-04-11 22:06 UTC, msftclas commented
@oakeyc,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-20 22:56 UTC, derekbekoe requested changes
One code style suggestion

2017-04-20 22:56 UTC, derekbekoe commented on azclishell/app.py
> +                    meaning = 'Failure'
Good candidate for a ternary operator here
http://book.pythontips.com/en/latest/ternary_operators.html#ternary-operators

2017-04-20 23:45 UTC, oakeyc commented on azclishell/app.py
> +                    meaning = 'Failure'
Good point

2017-04-20 23:47 UTC, derekbekoe approved these changes

2017-04-20 23:49 UTC, merged